language: python

python:
  - 3.6

addons:
  apt:
    packages:
      - gfortran

before_install:

  # Install Miniconda.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Install Python dependencies with conda using environment.yml.

  - conda env create --name plonk_dev --file environment.yml
  - source activate plonk_dev
  - conda install conda-build

install:

  - make
  - python setup.py build_ext --inplace
  - conda develop .

script:
  - python -m unittest discover

notifications:
  email:
    - d.mentiplay@gmail.com
