{% set data = load_setup_py_data() %}

package:
  name: plonk
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/dmentipl/plonk

requirements:
  build:
    - {{ compiler('fortran') }}
    - git
    - make
  host:
    - python=3
    - cython
    - numpy
    - setuptools
  run:
    - python=3
    - h5py
    - matplotlib
    - numpy
    - pandas
    - sympy

about:
  home: https://github.com/dmentipl/plonk
  license: MIT
  license_file: LICENSE
  summary: Smoothed particle hydrodynamics analysis and visualization
  description: |
    Plonk provides smoothed particle hydrodynamics analysis and visualization with Python.
  doc_url: https://plonk.readthedocs.io
  dev_url: https://github.com/dmentipl/plonk
