{% set data = load_setup_py_data() %}

package:
  name: plonk
  version: {{ data.get('version') }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    - dmentipl

requirements:
  host:
    - python>=3.6
    - setuptools
  run:
    - python>=3.6
    - KDEpy
    - astropy
    - h5py
    - matplotlib
    - numpy
    - pandas
    - pint
    - scikit-image>=0.16
    - scipy

about:
  home: {{ data["url"] }}
  license: {{ data["license"] }}
  summary: {{ data["description"] }}
  description: {{ data["long_description"] }}
  doc_url: https://plonk.readthedocs.io
