package:
  name: plonk
  version: '0.1'

source:
  path: ..

requirements:
  build:
    - python=3
    - cython
    - numpy
    - setuptools

  run:
    - python=3
    - h5py
    - matplotlib
    - numpy
    - pandas
    - sympy
